export const EXERCISE_NAME = {
  DUMBBELL_BENCH_PRESS: 'DUMBBELL_BENCH_PRESS',
  DUMBBELL_SHOULDER_PRESS: 'DUMBBELL_SHOULDER_PRESS',
  DUMBBELL_TRICEP_OVERHEAD_EXTENSION: 'DUMBBELL_TRICEP_OVERHEAD_EXTENSION',
  DUMBBELL_LATERAL_RAISE: 'DUMBBELL_LATERAL_RAISE',
  PLANK: 'PLANK',
  DUMBBELL_BENT_OVER_ROW: 'DUMBBELL_BENT_OVER_ROW',
  DUMBBELL_BICEP_CURL: 'DUMBBELL_BICEP_CURL',
  DUMBBELL_REVERSE_FLY: 'DUMBBELL_REVERSE_FLY',
  DUMBBELL_HAMMER_CURL: 'DUMBBELL_HAMMER_CURL',
  RUSSIAN_TWIST: 'RUSSIAN_TWIST',
  DUMBBELL_SQUAT: 'DUMBBELL_SQUAT',
  DUMBBELL_LUNGES: 'DUMBBELL_LUNGES',
  DUMBBELL_ROMANIAN_DEADLIFT: 'DUMBBELL_ROMANIAN_DEADLIFT',
  DUMBBELL_CALF_RAISE: 'DUMBBELL_CALF_RAISE',
  LEG_RAISES: 'LEG_RAISES',
  DUMBBELL_FRONT_RAISE: 'DUMBBELL_FRONT_RAISE',
  DUMBBELL_SHRUG: 'DUMBBELL_SHRUG',
  DUMBBELL_CONCENTRATION_CURL: 'DUMBBELL_CONCENTRATION_CURL',
  DUMBBELL_TRICEP_KICKBACK: 'DUMBBELL_TRICEP_KICKBACK',
  HOLLOW_BODY_HOLD: 'HOLLOW_BODY_HOLD',
  BURPEES: 'BURPEES',
  DUMBBELL_THRUSTER: 'DUMBBELL_THRUSTER',
  DUMBBELL_SWING: 'DUMBBELL_SWING',
  MOUNTAIN_CLIMBERS: 'MOUNTAIN_CLIMBERS',
  BICYCLE_CRUNCHES: 'BICYCLE_CRUNCHES',
} as const

export const INPUT_TYPE = {
  WEIGHT: 'WEIGHT',
  SECONDS: 'SECONDS',
  REPS: 'REPS',
} as const

export const WEEKDAY = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const
